# docker-compose.yml
version: '2'
services:
    prometheus:
        image: prom/prometheus:0.18.0
        volumes:
            - prometheus_data:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./alert.rules:/etc/prometheus/alert.rules
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
            - '-alertmanager.url=http://alertmanager:9093'
        ports:
            - '9090:9090'
    node-exporter:
        image: prom/node-exporter:0.12.0rc1
        ports:
            - '9100:9100'
    grafana:
        image: grafana/grafana:3.0.1
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=pass
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
    alertmanager:
        image: prom/alertmanager:0.1.1
        volumes:
            - ./alertmanager.yml:/alertmanager.yml
        command:
            - '-config.file=/alertmanager.yml'
volumes:
    prometheus_data: {}
    grafana_data: {}
